spring.application.name=expense-manager
spring.datasource.url=jdbc:mysql://localhost:3306/expensedb?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8089